# .streamlit/secrets.toml

# Clé API pour Anthropic Claude
# Remplacez cette valeur par votre véritable clé API Anthropic
ANTHROPIC_API_KEY = "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"

# Mot de passe pour accéder à l'application
# Remplacez cette valeur par le mot de passe de votre choix
APP_PASSWORD = "Demo"

# Vous pouvez ajouter d'autres secrets au besoin, par exemple:
# DATABASE_URL = "sqlite:///conversations.db"
