# .streamlit/secrets.toml

# Clé API pour Anthropic Claude
# Remplacez par votre véritable clé API
ANTHROPIC_API_KEY = "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"

# Mot de passe pour accéder à l'application
# Choisissez un mot de passe fort
APP_PASSWORD = "Demo"
