# .streamlit/secrets.toml

# Clé API pour Anthropic Claude
# Remplacez par votre véritable clé API
ANTHROPIC_API_KEY = "sk-ant-api03-VOTRE_CLE_API_ANTHROPIC_COMPLETE_ICI"

# Mot de passe pour accéder à l'application
# Choisissez un mot de passe fort
APP_PASSWORD = "votre_mot_de_passe_ici"
