# .streamlit/secrets.toml

# Clé API pour Anthropic Claude
# Remplacez par votre véritable clé API
ANTHROPIC_API_KEY = "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"

# Mot de passe pour accéder à l'application
# Choisissez un mot de passe fort
APP_PASSWORD = "Demo"
